# Generated by Django 4.0.6 on 2022-07-26 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('codigo_Categoria', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_c', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('codigo_us', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('codigo_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_p', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('precio', models.PositiveSmallIntegerField()),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('cod_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mibodega.categoria')),
                ('cod_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mibodega.usuario')),
            ],
        ),
    ]
