# Generated by Django 4.0.6 on 2022-07-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mibodega', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='codigo_Categoria',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
