# Generated by Django 4.0.6 on 2022-07-28 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mibodega', '0002_alter_categoria_codigo_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cod_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mibodega.categoria'),
        ),
    ]
