# Generated by Django 4.0.6 on 2022-07-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mibodega', '0003_alter_inventario_cod_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='codigo_inventario',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
