# Generated by Django 4.0.6 on 2022-07-28 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mibodega', '0004_alter_inventario_codigo_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cod_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mibodega.categoria'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cod_us',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mibodega.usuario'),
        ),
    ]
